name: Dependency Check

on: 
  workflow_run:
      workflows: [Web Deploy]
      types:
        - completed
        
jobs:
  depcheck:
    runs-on: ubuntu-latest
    name: dep_check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: npm run build
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
