# This is a basic workflow to help you get started with Actions

name: Web Deploy

on:
  release:
    branches: [ master ]
    
env:
  REPO_NAME: ${{ github.event.repository.name }}
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Env Setup
        run:  |
              echo "PRODUCT_NAME=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)" >> $GITHUB_ENV #NOTE: only works with SSH repo urls + will cause issues with bny_investments
              echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
              echo "PRODUCT_BASE=$(pwd)" >> $GITHUB_ENV
      
      - name: Sonar Setup
        run:  |
              echo "Sonar Setup:"
              date
              
              echo "sonar.projectKey="${{ env.REPO_NAME }} > sonar-project.properties
              echo "sonar.sources="${{ env.PRODUCT_BASE }}"/src" >> sonar-project.properties
      - name: Artifactory Setup
        run: |
              echo "Artifactory:"
              date
              #chmod 664 /usr/local/etc/npmrc
              npm config set @genesisglobal:registry https://genesisglobal.jfrog.io/artifactory/api/npm/npm-local/
              npm config set //genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:username ${{secrets.JFROG_RO_USER}}
              echo ${{secrets.JFROG_RO_USER}}@genesis.global | npm config set //genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:email
              npm config set //genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:always-auth true
              npm config set //genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:_auth ${{secrets.JFROG_NPM_AUTH_TOKEN}}
              #cp npmrc ~/.npmrc
              
      - name: Configure Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@genesislcap'
          
      - name: Cache Bootstrap
        id:   cache-bootstrap
        uses:  actions/cache@v2
        with:
          path: boots
          key: ${{ runner.os }}-bootstrap
          
      - name: Bootstrap
        if: steps.cache-bootstrap.outputs.cache-hit != 'true'
        run:  |
              echo "Bootstrap:"
              date
              npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}
          
      - name: Install
        run:  npm install
          
      - name: Build
        working-directory: packages/apps/${{ env.PRODUCT_NAME }}
        run: |
              echo "Building Prod:"
              echo $(pwd)
              date
              npm run build
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}
          
      - name: ESLint
        run: npm run lint:eslint:all
  
      - name: StyleLint
        run: npm run lint:stylelint:all
          
      - name: Package
        run:  |
              echo "Package:"
              date
              sudo apt-get install zip unzip
              echo $(pwd)
              ln -s packages/apps/${{ env.PRODUCT_NAME }}/src/ src		
              output=${{ env.PRODUCT_NAME }}-web-${{ env.VERSION }}.zip
              cd packages/apps/${{ env.PRODUCT_NAME }}/dist
              zip -r ${{ env.PRODUCT_BASE }}/$output *
              
      - name: Deploy
        run:  npm publish --verbose --registry https://genesisglobal.jfrog.io/artifactory/product/${PRODUCT_NAME}/web/${output}
