name: Server Test

on:
  push:
    branches: [ master ]
 
                          
jobs:
  build:
    runs-on: ubuntu-latest                                                                                                        
  
 
    steps:
      - uses: actions/checkout@v2                                                                                                                                        
      
      - name: Set up JDK                                                                                                                                                 
        uses: actions/setup-java@v1
        with:
          java-version: '11'
                   
      - name: Env Set-Up
        run: |
             echo "REPO_NAME=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f2 | xargs)" >> $GITHUB_ENV                                                               
             echo "PRODUCT_NAME= $(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f2 | cut -d"-" -f1 | xargs))" >> $GITHUB_ENV                                         
             echo "VERSION= $(git describe --tags)" >> $GITHUB_ENV
             echo "DISTRIBUTIONMANAGEMENT= $(grep "<distributionManagement>" -ic $(find . -maxdepth 1 -name pom.xml)))" >> $GITHUB_ENV 
             echo "JAVA_VERSION= $ (grep -m 1 "<kotlin.compiler.jvmTarget>" $(find . -maxdepth 1 -name pom.xml) | xargs | cut -d"/" -f1 | cut -d">" -f2 | rev | cut -c2- | rev)"  >> $GITHUB_ENV        
                                                          
             
      - name: Initialize                    
        run: echo 'POM version '
             echo $POM_VERSION
             echo 'Tag version '
             echo $VERSION
             echo "PATH = ${PATH}"
             echo "M2_HOME = ${M2_HOME}"
             echo "ARTIFACTORY_SETTINGS = ${ARTIFACTORY_SETTINGS}"
             mkdir -p $HOME/.m2
             cp -f $ARTIFACTORY_SETTINGS $HOME/.m2/settings.xml
        
      - name: 'Change to Java 1.8'                                                                                                          
        if: ${{'JAVA_VERSION' != '11'}}
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

                
